exclude: |
  ^(venv|env|\.tox|django_drip_campaigns\.egg-info|__pycache__|docs|legacy_docs|.*/migrations/.*\.py)$
default_stages: [commit]
fail_fast: true
default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--settings-path=setup.cfg"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: ["--config-file=setup.cfg"]
        additional_dependencies: [django-stubs, six]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: ["--config=pyproject.toml"]
