[tox]
env_list =
    3.8
    3.9
    3.10
    3.11
    3.12


[testenv:3.8]
description = Tests with python 3.8
basepython = python3.8.19
deps = 
    -rrequirements/test-requirements.txt
commands = pytest .


[testenv:3.9]
description = Tests with python 3.9
basepython = python3.9.19
deps = 
    -rrequirements/test-requirements.txt
commands = pytest .


[testenv:3.10]
description = Tests with python 3.10
basepython = python3.10.14
deps = 
    -rrequirements/test-requirements.txt
commands = pytest .


[testenv:3.11]
description = Tests with python 3.11
basepython = python3.11.9
deps = 
    -rrequirements/test-requirements.txt
commands = pytest .


[testenv:3.12]
description = Tests with python 3.12
basepython = python3.12.4
deps = 
    -rrequirements/test-requirements.txt
commands = pytest .
