# Generated by Django 3.1.7 on 2021-03-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drip", "0002_querysetrule_rule_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestUserUUIDModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
