# Generated by Django 3.0.7 on 2020-12-30 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('drip', '0003_drip_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drip',
            name='campaign',
            field=models.ForeignKey(blank=True, default=None, help_text='If set, this is the campaign to which this Drip belongs to.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='campaigns.Campaign'),
        ),
    ]
