# Generated by Django 3.2.13 on 2022-07-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0003_testuseruuidmodel'),
        ('drip', '0004_auto_20201230_2223'),
    ]

    operations = [
    ]
