# Generated by Django 3.2.14 on 2022-08-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0005_alter_querysetrule_lookup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='drip',
            name='can_resend_drip',
            field=models.BooleanField(default=False),
        ),
    ]
