# Generated by Django 3.2.14 on 2022-08-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0006_drip_can_resend_drip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drip',
            name='can_resend_drip',
            field=models.BooleanField(default=False, help_text='This will allow you to resend emails to users with the same Drip when query matches the user again.'),
        ),
    ]
