# Generated by Django 3.2.14 on 2022-08-05 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drip', '0007_alter_drip_can_resend_drip'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUnsubscribeDrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('drip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_unsubscribe_drips', to='drip.drip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_unsubscribe_drips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='drip',
            name='unsubscribed_users',
            field=models.ManyToManyField(related_name='drips_unsubscribed', through='drip.UserUnsubscribeDrip', to=settings.AUTH_USER_MODEL),
        ),
    ]
