# Generated by Django 3.2.14 on 2022-08-09 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drip', '0008_auto_20220805_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUnsubscribeCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_unsubscribe_campaigns', to='drip.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_unsubscribe_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='unsubscribed_users',
            field=models.ManyToManyField(related_name='campaign_unsubscribed_users', through='drip.UserUnsubscribeCampaign', to=settings.AUTH_USER_MODEL),
        ),
    ]
