# Generated by Django 3.2.14 on 2022-08-10 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drip', '0009_auto_20220809_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUnsubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_unsubscribes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
