# Generated by Django 3.0.7 on 2020-12-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Campaign', max_length=256)),
                ('delete_drips', models.BooleanField(default=True)),
            ],
        ),
    ]
