# Generated by Django 3.0.7 on 2020-12-17 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='name',
            field=models.CharField(default='Unnamed Campaign', max_length=256),
        ),
        migrations.AlterField(
            model_name='campaigndrip',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_drips', to='campaigns.Campaign'),
        ),
    ]
